apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
  labels:
    {{- include "homelab-backend.labels" . | nindent 4 }}
data:
  APP_ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  STARTUP_DELAY: "1s"
  SHUTDOWN_TIMEOUT: "10s"
  METRICS_AUTH_ENABLED: "true"
