apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: application-management

  source:
    repoURL: https://github.com/sotchenkov/devops-prac.git
    targetRevision: main
    path: argocd/application-sets

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
