- name: Install base packages
  ansible.builtin.import_tasks: packages.yml
  tags: packages

- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Configure time synchronization
  ansible.builtin.import_tasks: time.yml
  tags: time

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Configure kernel parameters
  ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- name: Configure Nginx and deploy static site
  ansible.builtin.import_tasks: nginx.yml
  tags: nginx
