- name: base server setup
  hosts: homelab
  remote_user: ansible
  gather_facts: false
  tasks:
   - name: configure sshd
     become: true
     ansible.builtin.copy:
       src: files/ssh/sshd_config
       dest: /etc/ssh/sshd_config
       owner: root
       group: root
       mode: '0644'
       validate: '/usr/sbin/sshd -t -f %s'
     notify:
       - reload ssh
   - name: install packages
     become: true
     ansible.builtin.apt:
       update_cache: true
       cache_valid_time: 3600
       pkg:
        - ca-certificates
        - curl
        - jq
        - unzip

  handlers:
  - name: reload ssh
    become: true
    ansible.builtin.service:
      name: ssh
      state: reloaded
