apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-backend-env
  namespace: homelab
  labels:
    app.kubernetes.io/name: app-backend
data:
  APP_ENVIRONMENT: "local"
  LOG_LEVEL: "info"
  STARTUP_DELAY: "1s"
  SHUTDOWN_TIMEOUT: "10s"
  METRICS_AUTH_ENABLED: "true"
  METRICS_TOKEN_FILE: "/run/secrets/BEARER_TOKEN"
