replicaCount: 2

image:
  repository: ghcr.io/sotchenkov/app-backend
  tag: "67c4ed58e5c673c88c484a2471fbe8719c8442f5"
  digest: "sha256:99640a9c2a6ec5e65e46801c522730d392ca80e906c74d2aeeee6aaf4e69157a"
  pullPolicy: IfNotPresent

config:
  environment: local
  logLevel: info

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "32Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"