replicaCount: 2

image:
  repository: ghcr.io/sotchenkov/app-backend
  tag: 5edb397fa066a0695b61e635b8d7be930112efd5
  digest: sha256:bb12fc4a58ed37a6ebd4d51317c8c5bb5798fa413ab2270d0553d68ff414f406
  pullPolicy: IfNotPresent

config:
  environment: stage
  logLevel: warn

resources:
  limits:
    cpu: "400m"
